customCommands:
  - key: "W"
    context: "files"
    command: 'git commit -m "{{ .Form.commit_msg }}" --no-verify'
    description: "Commit without verification"
    prompts:
      - type: "input"
        title: "Commit message:"
        key: "commit_msg"
        initialValue: "wip"

  - key: "<c-d>"
    context: "files"
    description: "Generate git patch from changes"
    prompts:
      - type: "input"
        title: "Enter file path for patch to be saved (relative to repo root)"
        key: "file"
    command: >
      bash -c 'git diff HEAD --cached > "{{.Form.file}}.patch" && echo "✅ Patch saved as {{.Form.file}}.patch"'
gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#e89bc1"
      - bold
    inactiveBorderColor:
      - "#928da0"
    optionsTextColor:
      - "#7ba5dd"
    selectedLineBgColor:
      - "#302a3a"
    cherryPickedCommitBgColor:
      - "#4d3a5a"
    cherryPickedCommitFgColor:
      - "#d4956e"
    unstagedChangesColor:
      - "#e87b97"
    defaultFgColor:
      - "#d0cbd8"
    searchingActiveBorderColor:
      - "#d9b464"

  authorColors:
    "*": "#c48ad5"
