# ~/.config/hypr/hypridle.conf

general {
    lock_cmd = qs -c noctalia-shell ipc call lockScreen lock           # what to run when locking
    before_sleep_cmd = qs -c noctalia-shell ipc call lockScreen lock   # lock before sleep (optional, but good!)
    after_sleep_cmd = hyprctl dispatch dpms on   # wake display after resume
}

listener {
    timeout = 600                       # 10 minutes
    on-timeout = hyprctl dispatch dpms off # turn off display
    on-resume = hyprctl dispatch dpms on  # turn on display on activity
}

listener {
    timeout = 300                 # idle time in seconds (5 min)
    on-timeout = qs -c noctalia-shell ipc call lockScreen lock        # what to do at timeout
    on-resume = hyprctl dispatch dpms on
}

# Disabled - NVIDIA has suspend/resume issues, use WOL instead
# listener {
#     timeout = 43200                 # 8 hours
#     on-timeout = systemctl suspend
#     on-resume = hyprctl dispatch dpms on
# }
