
$rosewater = rgb(e89bc1)
$rosewaterAlpha = e89bc1

$flamingo = rgb(d8a0e8)
$flamingoAlpha = d8a0e8

$pink = rgb(e89bc1)
$pinkAlpha = e89bc1

$mauve = rgb(c48ad5)
$mauveAlpha = c48ad5

$red = rgb(e87b97)
$redAlpha = e87b97

$maroon = rgb(f09aae)
$maroonAlpha = f09aae

$peach = rgb(d4956e)
$peachAlpha = d4956e

$yellow = rgb(d9b464)
$yellowAlpha = d9b464

$green = rgb(7cc9a0)
$greenAlpha = 7cc9a0

$teal = rgb(57bfb5)
$tealAlpha = 57bfb5

$sky = rgb(6dd8ce)
$skyAlpha = 6dd8ce

$sapphire = rgb(96bef0)
$sapphireAlpha = 96bef0

$blue = rgb(7ba5dd)
$blueAlpha = 7ba5dd

$lavender = rgb(d8a0e8)
$lavenderAlpha = d8a0e8

$text = rgb(d0cbd8)
$textAlpha = d0cbd8

$subtext1 = rgb(bdb8cb)
$subtext1Alpha = bdb8cb

$subtext0 = rgb(928da0)
$subtext0Alpha = 928da0

$overlay2 = rgb(928da0)
$overlay2Alpha = 928da0

$overlay1 = rgb(4d465a)
$overlay1Alpha = 4d465a

$overlay0 = rgb(4d465a)
$overlay0Alpha = 4d465a

$surface2 = rgb(4d3a5a)
$surface2Alpha = 4d3a5a

$surface1 = rgb(302a3a)
$surface1Alpha = 302a3a

$surface0 = rgb(302a3a)
$surface0Alpha = 302a3a

$base = rgb(1a1721)
$baseAlpha = 1a1721

$mantle = rgb(14111b)
$mantleAlpha = 14111b

$crust = rgb(0e0b15)
$crustAlpha = 0e0b15
